/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package aip.niopdc.sellbi.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import rex.DimensionMember;

/** 
 * MyEclipse Struts
 * Creation date: 09-16-2009
 * 
 * XDoclet definition:
 * @struts.form name="saletrendinlocation1Form"
 */
public class Saletrendinlocation1Form extends ActionForm {
	String defaultLocation=""; 
	int defaultType = 1;
	int defaultMeasureInt=1;
	DimensionMember[] locationCombos=new DimensionMember[0];
	
	
	
	/*
	 * Generated Methods
	 */

	public DimensionMember[] getLocationCombos() {
		return locationCombos;
	}

	public void setLocationCombos(DimensionMember[] locationCombos) {
		this.locationCombos = locationCombos;
	}

	public String getDefaultLocation() {
		return defaultLocation;
	}

	public void setDefaultLocation(String defaultLocation) {
		this.defaultLocation = defaultLocation;
	}

	public int getDefaultType() {
		return defaultType;
	}

	public void setDefaultType(int defaultType) {
		this.defaultType = defaultType;
	}

	public int getDefaultMeasureInt() {
		return defaultMeasureInt;
	}

	public void setDefaultMeasureInt(int defaultMeasureInt) {
		this.defaultMeasureInt = defaultMeasureInt;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}