/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package aip.niopdc.sellbi.struts.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;


import com.tonbeller.jpivot.olap.model.OlapException;
import com.tonbeller.jpivot.xmla.XMLA_OlapItem;
import com.tonbeller.jpivot.xmla.XMLA_SOAP;

import aip.tag.tree.AIPTree;
import aip.util.NVL;
import aip.util.UTF8;
import aip.xmla.AIPOlap;

/** 
 * MyEclipse Struts
 * Creation date: 09-26-2009
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class Members2Action extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		//response.setCharacterEncoding("utf8");
		response.setContentType("text/html");

		String _User ="";
		String _Password="";

		try {
			XMLA_SOAP xmla_soap=new XMLA_SOAP(AIPOlap.getDataSourceURI(),_User,_Password);
			
			String reqCode = NVL.getEmptyString(request.getParameter("reqCode"),"dimensions");
			String id=UTF8.cnvUTF8( request.getParameter("id") );
			
			System.out.println("Members2Action.execute():reqCode="+reqCode+",querystring="+ request.getQueryString());

			PrintWriter out = response.getWriter();
			String text="", url,oid="";
		
			//String nodeType = NVL.getString(request.getParameter("nodeType"), "DEFAULT");
			if("dimensions".equalsIgnoreCase(reqCode)){
				List<XMLA_OlapItem> lstDimensions=null;
				lstDimensions=xmla_soap.discoverDim( AIPOlap.getCatalog(), AIPOlap.getCubeName());

				for (XMLA_OlapItem dim : lstDimensions) {
					oid = dim.getUniqueName();
					text = dim.getCaption();
					url = "members2.do?reqCode=dimension&id="+oid;
					AIPTree.appendTreeNode(out, text, url, "dbclickCreateQuery(reportQuery,this);",oid);
				}			
			}else if("dimension".equalsIgnoreCase(reqCode)){
				List<XMLA_OlapItem> lstHierarchies=null;
				lstHierarchies=xmla_soap.discoverHier(AIPOlap.getCatalog(),AIPOlap.getCubeName(), id);

				for (XMLA_OlapItem hierarchy : lstHierarchies) {
					oid = hierarchy.getUniqueName();
					text = hierarchy.getCaption();
					url = "members2.do?reqCode=hierarchy&id="+oid+"&dim="+id;
					AIPTree.appendTreeNode(out, text, url, "dbclickCreateQuery(reportQuery,this);",oid);
				}			
			}else if("hierarchy".equalsIgnoreCase(reqCode)){
				List<XMLA_OlapItem> lstMembers=null;
				lstMembers=xmla_soap.discoverMemTree(AIPOlap.getCatalog(),AIPOlap.getCubeName(), id+".[All]",1);
				for (XMLA_OlapItem member : lstMembers) {
					oid = member.getUniqueName().replace("&", "%26");
					text = member.getCaption();
					url = "members2.do?reqCode=member&id="+oid+"&parent="+id+".[همه]";
					System.out.println("Members2Action.execute():url="+url);
//					if(member.getChildrenCount()>0){
						AIPTree.appendTreeNode(out, text, url, "dbclickCreateQuery(reportQuery,this);",oid);
//					}else{
//						AIPTree.appendTreeNodeLeaf(out, text,"",id);
//					}
				}			
			}else if("member".equalsIgnoreCase(reqCode)){
				List<XMLA_OlapItem> lstMembers=null;
				System.out.println("Members2Action.execute():parent="+id);
				lstMembers=xmla_soap.discoverMemTree(AIPOlap.getCatalog(),AIPOlap.getCubeName(), id,1);
				for (XMLA_OlapItem member : lstMembers) {
					oid = member.getUniqueName().replace("&", "%26");;
					text = member.getCaption();
					url = "members2.do?reqCode=member&id="+oid+"&parent="+id;
					System.out.println("Members2Action.execute():url="+url);
//					if(member.getChildrenCount()>0){
						AIPTree.appendTreeNode(out, text, url, "dbclickCreateQuery(reportQuery,this);",oid);
//					}else{
//						AIPTree.appendTreeNodeLeaf(out, text,"",id);
//					}
				}			
			}else{
			}
		} catch (IOException e) {
			e.printStackTrace();
		} catch (OlapException e) {
			e.printStackTrace();
		}
		
		return null;
	}
}