/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package aip.niopdc.sellbi.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.config.ForwardConfig;

import aip.jpivot.AIPPivotParam;
import aip.niopdc.sellbi.struts.form.Saletrendinlocation1Form;
import aip.util.NVL;
import aip.xmla.AIPOlap;

import rex.DimensionMember;

/** 
 * MyEclipse Struts
 * Creation date: 09-16-2009
 * 
 * XDoclet definition:
 * @struts.action
 * @struts.action-forward name="view" path="/saletrendinlocation1.jsp"
 */
public class Saletrendinlocation1Action extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HttpSession session = request.getSession();
		Saletrendinlocation1Form saletrendinlocation1Form=(Saletrendinlocation1Form)form;
		if(saletrendinlocation1Form!=null){
			saletrendinlocation1Form=new Saletrendinlocation1Form();
		}

		AIPPivotParam param = new AIPPivotParam();
		param.setFormAction("sale_trend_in_location1.jsp");
		param.setQueryName("sale_trend_in_location1");
		
		String whereClause="";
		String reqCode=request.getParameter("reqCode");

		int _oldMeasureInt=NVL.getInt(session.getAttribute("sale_trend_in_location_measure"),1);
		session.setAttribute("sale_trend_in_location_measure",saletrendinlocation1Form.getDefaultMeasureInt());

		if( ( reqCode!=null && "filter".equalsIgnoreCase(reqCode)) || (saletrendinlocation1Form.getDefaultMeasureInt()!=_oldMeasureInt) ){
			session.setAttribute(param.getQueryName(),null);
			session.setAttribute("tbl"+param.getQueryName(),null);

			if(!"".equals(saletrendinlocation1Form.getDefaultLocation()) || saletrendinlocation1Form.getDefaultType()>0){
				whereClause =" ";
				if(!"".equals(saletrendinlocation1Form.getDefaultLocation()))
					whereClause+="where ( [مناطق].[منطقه- ناحیه].&["+saletrendinlocation1Form.getDefaultLocation()+"] )";
			}
		}
			
		
		
	//defaultMeasureInt = NVL.getInt(request.getParameter("measure"),1);
	
	
	String defaultMeasure="";
	switch(saletrendinlocation1Form.getDefaultMeasureInt()){
		case 1:
			defaultMeasure="[Measures].[مبلغ کل]";
			break;
		case 2:
			defaultMeasure="[Measures].[مبلغ فیش]";
			break;
		case 3:
			defaultMeasure="[Measures].[مقدار]";
			break;
		case 4:
			defaultMeasure="[Measures].[ در صد افزایش مبلغ کل]";
			break;
		case 5:
			defaultMeasure="[Measures].[در صد افزایش مبلغ فیش]";
			break;
		case 6:
			defaultMeasure="[Measures].[درصد افزایش مقدار]";
			break;
		default:
			defaultMeasure="[Measures].[مبلغ کل]";
			break;
	}
	
//out.println("whereClause="+whereClause);
	saletrendinlocation1Form.setLocationCombos( AIPOlap.getDimTreeMembers("[مناطق]"
			,"[مناطق].[منطقه- ناحیه]"
			,"[مناطق].[منطقه- ناحیه].[Level 02]") );
	
	param.setMdxQuery("SELECT {"+ defaultMeasure +"} on columns,"
		       +" {DESCENDANTS( [زمان].[سال-فصل-ماه],"+ saletrendinlocation1Form.getDefaultType() +",SELF)} on rows"
		+"from [حواله]"+whereClause);

	
	request.setAttribute("AIPPivotParam",param);
	request.setAttribute("saletrendinlocation1Form", saletrendinlocation1Form);
	
	

		return new ActionForward("/test.jsp",false);
		
		//return mapping.findForward("view");
	}
}